### ISSUE TITLE
Double check implementation?

### ISSUE THREAD

**Issue by cabello** [jetify-com/typeid-js#1]
Using this tool: https://cryptii.com/pipes/crockford-base32

![CleanShot 2023-06-29 at 20 45 27@2x](https://github.com/jetpack-io/typeid-ts/assets/60936/b0ab3749-c6cf-4e39-9fd4-e45c14f1a156)

But the tests for the same input shows: 

https://github.com/jetpack-io/typeid-ts/blob/091938da886f4d944a685158f9ea4fbcbfdbe1e0/test/typeid.test.ts#L114-L117

I was porting the code to Elixir using https://hex.pm/packages/crockford_base32 and the result from the library matches the online tool but does not match the Typescript implementation.

```elixir
test "encode" do
  assert Typeid.encode("user", "01889c89-df6b-7f1c-a388-91396ec314bc") == {
           :ok,
           "user_0649s2ezddzhs8w8j4wpxgrmqg"
         }
end
```

**Comment by loreto** [comment]
Hi @cabello,

Thanks for reporting – I've added a ton of tests at this point, so I'm pretty certain the current implementation is "correct" (but it of course depends on what we define correct to be).

The encoding question has come up a few times and here's what we've learned:
1. Due to padding, there's different ways to implement a base32 encoding.
2. I've formalized the way TypeID implementations should do it in this document https://github.com/jetpack-io/typeid/tree/main/spec#base32-encoding
3. What it means in practice is that we implement the encoding the same way `ulid` does (so if you're looking to check your work against an online example, you're better off checking with something https://www.ulidtools.com/). It also means that we use crockford's _alphabet_ in our encoding, but not the full set of Crockford rules.

You might ask, why do it the ulid way and not the default base32 encoding way? The reason is so that the `typeid` representation and the `uuid` representation align with each other in the following way:
- `prefix_00000000000000000000000000` <=> `00000000-0000-0000-0000-000000000000`
- `prefix_00000000000000000000000001` <=> `00000000-0000-0000-0000-000000000001`
- `prefix_0000000000000000000000000g` <=> `00000000-0000-0000-0000-000000000010`

To make this all easier to implement I've also added testdata to the spec, that people can use to test their implementations:
- https://github.com/jetpack-io/typeid/blob/main/spec/valid.yml for data that should be considered valid
- https://github.com/jetpack-io/typeid/blob/main/spec/invalid.yml for data that should be considered invalid

Hope that helps!

**Comment by cabello** [comment]
@loreto I found the spec today and it was quite useful, turns out the tool is also wrong, I mean wrong in terms of interpretation bytes vs text, etc.

I found a way around the dependencies that I am using that match the implementation specially the basic ones that makes total sense, e.g. test cases one, ten, sixteen.

Closing for now. Thank you
