### ISSUE TITLE
Typed `toString()`?

### ISSUE THREAD

**Issue by DanHulton** [jetify-com/typeid-js#8]
Typescript, since 4.1, allows for string templates such as `\`user_${string}\``.  I've taken advantage of this to create "string types" to pair with my TypeID types:

```ts
export type UserTypeString = `user_${string}`;
export type UserTypeID = TypeID<'user'>;

// ...

private connectedUsers: Record<UserTypeString, User> = {};
```

You can't use `UserTypeID` as an index, but you _can_ use `UserTypeString`, and it makes it a lot clearer exactly what you're keying by.

However, later, when you do something like this, it will fail:

```ts
const userId = user.id.toString();
connectedUsers[userId] = user;
```

`toString()` returns a `string`, but I want it to return a `user_${string}`.  For now, I'm planning on subclassing TypeID in my project and overriding the `toString()` function to work the way I want, but is this something there would be interest in having added to the base library?

Specifically, I've added:

```ts
  public toTypeString(): `${T}_${string}` {
    return this.toString() as `${T}_${string}`;
  }
```

Instead of modifying `toString()`, since that'll break everything that is expecting a regular `string` from that function.  This seems like a pretty simple little addition that gives a fair extra bit of clarity when using the string form of TypeIDs as indexes.

**Comment by pocketarc** [comment]
Would it break anything, though? Off the top of my head I can't think of a reason why something that expects a `string` would break when given a templated string, instead. It -should- be safe to change toString().

But I do agree with the idea of using templated strings. It's minor, but it's nice.

**Comment by DanHulton** [comment]
Hm, I assumed it would, but then I just tried assigning a templated string to a variable that has been explicitly defined as a string and it worked just fine.  Which makes sense now that I think about it (after you've mentioned it), a templated string satisfies the requirements for a string perfectly well.

**Comment by DanHulton** [comment]
Okay, so I checked out `typeid-js` locally and modified `toString` to the following:

```ts
  public toString(): `${T}_${string}` {
    if (this.prefix === "") {
      return this.suffix as `${T}_${string}`;
    }
    return `${this.prefix}_${this.suffix}` as `${T}_${string}`;
  }
```

And it works exactly as expected, tests all pass, easy as Sunday morning.  I can put up a PR against the monorepo, if that looks good to you?

**Comment by pocketarc** [comment]
I'm not a contributor, just a random watcher, otherwise I'd happily merge it. 😉 But one thing that's worth noting is that if `this.prefix` is empty, then the result is -not- `${T}_${string}` (that would be `_string`, which is wrong).

So the return value should be something like:

```
T extends "" ? `${string}` : `${T}_${string}`
```

A step further might also be to promote the 'suffix' to a proper type in the class, otherwise you're never going to get a reliable type out of it (although that is probably way beyond the scope of what you're wanting to do).

It's the difference between these two:

![image](https://github.com/jetpack-io/typeid-js/assets/5393/52f50cf4-1a99-456a-9410-94613e2d0129)

![image](https://github.com/jetpack-io/typeid-js/assets/5393/1b9c3b02-eac4-40ce-9391-5744d9889080)

**Comment by DanHulton** [comment]
Okay, put up a PR here, in case you're interested in using it when/if it gets merged and released: https://github.com/jetpack-io/opensource/pull/261

On the topic of promoting suffix to proper type, I'm not sure I understand the value there?  Typing based on prefix allows me to ensure I have _some kind_ of user ID, and any other ID will fail.  Typing based on suffix would ensure I have _exactly one user's ID_, and any other user's ID would fail.  If I want to restrict code based on a single entity's ID, like for a hard-coded superuser, I can always do something like `if (user.id.toString() === SUPERUSER_ID)`, but even that feels like the kind of thing you do for a little while when prototyping, not something that lives beyond any serious "okay now we add proper user privileges" pass, and not something that needs to be encoded in the type system.  Unless I'm missing some use case for this entirely (always possible!)?

**Comment by pocketarc** [comment]
For me it's more so that type info isn't lost; in the 2nd screenshot above you can see that TypeScript lost information on the return value, it thinks that the return value is just `string`, an arbitrary string. But it's not an arbitrary string, we know what the string is.

When I do `typeid("foo", "bar").toString()`, the return type shouldn't be broadened to an arbitrary `string`, it should be `"foo_bar"`, because... we know it is. It doesn't have anything to do with permissions or comparing user IDs.

I do agree that the value of such a change is minimal, though, it's not going to hurt anyone either way. I don't really care about it, and it requires a bigger refactor than just what you were suggesting, so it's probably not worth it.

----

Also, I've read the PR, and I'm afraid it's still iffy; now it returns `${T}_${string} | string`, but.. that's not true; if T is an empty string, then it doesn't return `${T}_${string} | string`, it returns `string`. That's why I suggested it being based on `T extends ""`, because otherwise it doesn't resolve types correctly, making this change less useful.

You can see how TypeScript views the type from your PR, below. It's just an arbitrary string, it's no different than before.

![image](https://github.com/jetpack-io/typeid-js/assets/5393/de747064-6a69-4b8b-b534-ddb0a05eba65)

The following resolves it:

```typescript
  public toString() {
    if (this.prefix === "") {
      return this.suffix as (T extends "" ? string : `${T}_${string}`);
    }
    return `${this.prefix}_${this.suffix}` as (T extends "" ? string : `${T}_${string}`);
  }
```

![image](https://github.com/jetpack-io/typeid-js/assets/5393/8d905c49-f27e-41f6-a5af-9b436fc01c83)

**Comment by loreto** [comment]
@LucilleH will take a look at the proposal and we'll reply back in this same thread

**Comment by DanHulton** [comment]
Hm, I'm curious what you're using to test that, @pocketarc!  With only my changes, I see this:

<img width="528" alt="Screenshot 2024-01-22 at 12 06 25 PM" src="https://github.com/jetpack-io/typeid-js/assets/382432/fce67f71-83c8-45c3-903e-38efa6408653">

As I understand Typescript's type narrowing, it should be able to infer based on that `if (this.prefix === "")` what type is being returned - the plain string or the typed template, which is indeed what I see in my editor (Webstorm, FWIW, but it run type checking through external Typescript tools).

In fact, the `as (T extends "" ? string : `${T}_${string}`)` in your latest example, isn't that redundant?  Inside the `if`, `T` is ALWAYS empty, so it would always return a `string`.  Outside of it, `T` is NEVER empty, so it always returns the templated string.  So is the ternary necessary?

**Comment by DanHulton** [comment]
Oh, actually maybe I shouldn't close it until there's a publish of the package.  My bad, jumped the gun!

**Comment by LucilleH** [comment]
0.5.0 published.
